"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from typing import Any

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


#Explicitly point to the .env file in the backend directory
load_dotenv(dotenv_path=BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'your-default-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# Comma-separated host list, e.g. "yourdomain.com,www.yourdomain.com". In DEBUG
# an empty value auto-trusts localhost/127.0.0.1 dev hosts.
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('ALLOWED_HOSTS', '').split(',')
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'agent',
    'user',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# --- Silent session auth (cookie) hardening -------------------------------
# The browser's Auth is a lightweight HttpOnly session cookie - no heavy login
# machinery. Keep it HttpOnly + SameSite and force over HTTPS outside DEBUG.
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = not DEBUG
# CSRF cookie must be readable by the frontend SPA (it sends `X-CSRFToken`) while
# the session cookie above stays HttpOnly. This is the standard Django SPA split.
CSRF_COOKIE_HTTPONLY = False
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get('TRUSTED_ORIGINS', '').split(',')
    if o.strip()
]

# --- CORS configuration --------------------------------------------------
# Allow the frontend to make cross-origin requests to this backend.
# Default allows localhost:3000 for development; extend via CORS_ALLOWED_ORIGINS env var.
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:3000').split(',')
    if o.strip()
]
CORS_ALLOW_CREDENTIALS = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'config.middleware.DisableCsrfForApi',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# --- Dynamic database gateway -------------------------------------------------
# Render (production) injects a ``DATABASE_URL`` pointing at Neon PostgreSQL.
# When present we use that (with pgvector); otherwise we fall back to SQLite for
# local development/testing (in-memory by default).
def _database_gateway() -> dict[str, Any]:
    """Pick the DB engine from the environment at runtime.

    - ``DATABASE_URL`` present  -> PostgreSQL (Neon + pgvector), production.
    - Unix socket / debug mode  -> in-memory SQLite for dev/test.
    Set ``SQLITE_PATH`` to persist the local DB to a file (e.g. ``db.sqlite3``).
    """
    database_url = os.environ.get("DATABASE_URL", "").strip()
    if database_url:
        try:
            import dj_database_url

            config = dj_database_url.parse(
                database_url, conn_max_age=600, ssl_require=True
            )
            config["ENGINE"] = "django.db.backends.postgresql"
            return dict(config)
        except Exception as exc:  # pragma: no cover - defensive  # noqa: BLE001
            import warnings

            warnings.warn(f"DATABASE_URL set but invalid; falling back to SQLite: {exc}")
            os.environ.pop("DATABASE_URL", None)

    # Local development / testing fallback (in-memory SQLite by default).
    sqlite_path = os.environ.get("SQLITE_PATH", "").strip()
    return {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": (Path(sqlite_path) if sqlite_path else ":memory:"),
    }


DATABASES = {
    "default": _database_gateway(),
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# Standard Django email backend (console during development).
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# ---------------------------------------------------------------------------
# Autonomous trading agent configuration
# ---------------------------------------------------------------------------
# Default the agent to SAFE defaults: DRY_RUN + heuristic only. Flip AGENT_* env
# vars (or override per-call via the API) to enable the LLM and live execution.
AGENT_CONFIG = {
    # In dry-run the agent analyses and simulates but never submits orders.
    'dry_run': os.environ.get('AGENT_DRY_RUN', 'True').lower() in ('1', 'true', 'yes'),
    'heuristic_only': os.environ.get('AGENT_HEURISTIC_ONLY', 'True').lower()
    in ('1', 'true', 'yes'),
    # Lighter risk button lowered for a hackathon-sized paper account.
    'min_equity_for_hedge': os.environ.get('AGENT_MIN_EQUITY', '1000'),
    'max_drawdown_ratio': os.environ.get('AGENT_MAX_DRAWDOWN', '0.10'),
    'target_coverage_ratio': os.environ.get('AGENT_TARGET_COVERAGE', '1.0'),
    'protection_floor_ratio': os.environ.get('AGENT_FLOOR', '0.90'),
    'premium_budget_ratio': os.environ.get('AGENT_PREMIUM_BUDGET', '0.02'),
    'hedge_days_to_expiry': int(os.environ.get('AGENT_HEDGE_DAYS', '30')),
    'market_close_skip': True,
    # Autonomous position-opening controls (flip AGENT_AUTO_OPEN=1 to enable).
    'max_position_pct': os.environ.get('AGENT_MAX_POSITION_PCT', '0.10'),
    'max_positions': int(os.environ.get('AGENT_MAX_POSITIONS', '5')),
    'min_cash_reserve': os.environ.get('AGENT_MIN_CASH_RESERVE', '5000'),
    'auto_open_positions': os.environ.get('AGENT_AUTO_OPEN', 'False').lower()
    in ('1', 'true', 'yes'),
    # Optional LLM. Fireworks is primary (https://api.fireworks.ai/inference/v1),
    # Featherless is the automatic fallback (https://api.featherless.ai/v1); both
    # are OpenAI-compatible. Leave both keys blank to stay heuristic.
    'llm_provider': os.environ.get('AGENT_LLM_PROVIDER', 'fireworks'),
    'llm_model': os.environ.get('AGENT_LLM_MODEL', 'accounts/fireworks/models/deepseek-v4-flash-0731'),
    'llm_api_key': (
        os.environ.get('FIREWORKS_API_KEY')
        or os.environ.get('FEATHERLESS_API_KEY', '')
    ),
    'llm_base_url': os.environ.get('AGENT_LLM_BASE_URL', ''),
    # Alpaca MCP connection
    'mcp_command': os.environ.get('AGENT_MCP_COMMAND', ''),
    'toolsets': 'account,trading,assets,options-data,stock-data',
}
