# Generated by Django 6.1 on 2026-08-31 19:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('auto_approvisioned', models.BooleanField(default=False, help_text='True for the env-seeded default profile created at bootstrap.')),
                ('api_key', models.TextField(blank=True, default='')),
                ('secret_key', models.TextField(blank=True, default='')),
                ('base_url', models.CharField(blank=True, default='https://paper-api.alpaca.markets', max_length=256)),
                ('data_url', models.CharField(blank=True, default='https://data.alpaca.markets', max_length=256)),
                ('paper', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
    ]
