# Generated by Django 6.1 on 2026-09-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agent_auto_open',
            field=models.BooleanField(blank=True, default=None, help_text='Let the agent buy stock / sell cash-secured puts on its own.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agent_dry_run',
            field=models.BooleanField(blank=True, default=None, help_text='Simulate decisions without submitting real orders.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agent_heuristic_only',
            field=models.BooleanField(blank=True, default=None, help_text='Skip the LLM and use the deterministic heuristic fallback.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agent_max_position_pct',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, help_text='Max %% of equity per stock position (e.g. 0.10 = 10%%).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agent_max_positions',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Max concurrent stock positions the agent may hold.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='agent_min_cash_reserve',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Cash floor the agent must never trade below.', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
