# Generated by Django 6.1 on 2026-08-28 19:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [  # noqa: RUF012
    ]

    operations = [  # noqa: RUF012
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Agent configuration',
                'verbose_name_plural': 'Agent configurations',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_id', models.UUIDField(db_index=True)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('action', models.CharField(choices=[('hold', 'Hold'), ('hedge', 'Hedge (protective put)'), ('unwind', 'Unwind / reduce risk'), ('emergency', 'Emergency flat'), ('close_hedge', 'Close hedge')], default='hold', max_length=32)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('summary', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('risk_snapshot', models.JSONField(blank=True, default=dict)),
                ('degraded', models.BooleanField(default=False, help_text='True if heuristic, not LLM')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hedge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('underlying', models.CharField(db_index=True, max_length=16)),
                ('occ_symbol', models.CharField(max_length=64)),
                ('contracts', models.IntegerField(default=0)),
                ('strike', models.DecimalField(decimal_places=4, max_digits=20)),
                ('expiry', models.DateField()),
                ('premium_total', models.DecimalField(decimal_places=2, default=0, help_text='Total cost of the puts (debit)', max_digits=20)),
                ('protection_floor', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('closed', 'Closed'), ('expired', 'Expired')], default='open', max_length=16)),
                ('order_id', models.CharField(blank=True, max_length=64)),
                ('current_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_id', models.UUIDField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('message', models.TextField(blank=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptionPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occ_symbol', models.CharField(help_text='OCC option symbol, e.g. AAPL250321C00150000', max_length=64, unique=True)),
                ('underlying', models.CharField(db_index=True, max_length=16)),
                ('option_type', models.CharField(choices=[('C', 'Call'), ('P', 'Put')], max_length=1)),
                ('strike', models.DecimalField(decimal_places=4, max_digits=20)),
                ('expiry', models.DateField(db_index=True)),
                ('qty', models.IntegerField(default=0, help_text='Number of contracts')),
                ('side', models.CharField(default='buy', max_length=16)),
                ('avg_entry_price', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('mark_price', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('market_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('unrealized_pl', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('implied_vol', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('delta', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('gamma', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('theta', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('vega', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('is_hedge', models.BooleanField(default=False, help_text='True if opened by the risk engine')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('expired', 'Expired')], db_index=True, default='open', max_length=16)),
            ],
            options={
                'ordering': ['underlying', 'expiry', 'strike'],
            },
        ),
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('client_order_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('symbol', models.CharField(db_index=True, max_length=64)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=8)),
                ('order_type', models.CharField(default='market', max_length=32)),
                ('qty', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('filled_avg_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('notional', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('status', models.CharField(db_index=True, default='new', max_length=32)),
                ('strategy', models.CharField(choices=[('protective_put', 'Protective Put'), ('hedge', 'Hedge'), ('unwind', 'Unwind'), ('emergency_flat', 'Emergency flat'), ('manual', 'Manual')], default='manual', max_length=32)),
                ('is_hedge', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('brain', 'Brain'), ('emergency_cli', 'Emergency CLI'), ('manual', 'Manual')], default='brain', max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equity', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('buying_power', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('long_market_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('unrealized_pl', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('day_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('num_positions', models.IntegerField(default=0)),
                ('num_option_positions', models.IntegerField(default=0)),
                ('at_risk_exposure', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('hedge_coverage_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(db_index=True, max_length=32, unique=True)),
                ('asset_class', models.CharField(choices=[('stock', 'Stock / ETF'), ('crypto', 'Crypto'), ('us_option', 'US Option')], default='stock', max_length=16)),
                ('side', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], default='long', max_length=8)),
                ('qty', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('avg_entry_price', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('current_price', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('market_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('unrealized_pl', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('unrealized_plpc', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
    ]
