# Generated by Django 6.1 on 2026-08-30 09:40

import uuid

import django.utils.timezone
from django.db import migrations, models

import agent.models


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012
        ('agent', '0001_initial'),
    ]

    operations = [  # noqa: RUF012
        migrations.CreateModel(
            name='EmbeddedRiskContext',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_title', models.CharField(blank=True, default='', max_length=255)),
                ('raw_text_chunk', models.TextField(help_text='One chunk of ingested perception text (agent-facing).')),
                ('embedding_vector', agent.models.VectorStoreField(dimensions=1536, help_text='pgvector embedding of ``raw_text_chunk`` (text -> vector).')),
                ('ticker_scope', models.CharField(blank=True, db_index=True, default='', help_text='Ticker this chunk pertains to (blank = whole account).', max_length=16)),
                ('sentiment_tag', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], default='', help_text='Optional sentiment label assigned to the chunk.', max_length=16)),
                ('source', models.CharField(choices=[('account', 'Account'), ('positions', 'Positions'), ('stock_bars', 'Stock historical bars'), ('option_chain', 'Option chain'), ('option_snapshot', 'Option snapshot'), ('decision', 'Agent decision')], db_index=True, default='positions', help_text='Which kind of perception data produced this chunk.', max_length=32)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Market-data timestamp of the source snapshot.', null=True)),
                ('ingested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-ingested_at'],
            },
        ),
        migrations.DeleteModel(
            name='AgentConfig',
        ),
        migrations.RemoveField(
            model_name='optionposition',
            name='gamma',
        ),
        migrations.RemoveField(
            model_name='optionposition',
            name='theta',
        ),
        migrations.RemoveField(
            model_name='optionposition',
            name='vega',
        ),
    ]
