# Generated by Django 6.1 on 2026-08-31 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_embeddedriskcontext_delete_agentconfig_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decision',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='embeddedriskcontext',
            options={'ordering': ('-ingested_at',)},
        ),
        migrations.AlterModelOptions(
            name='hedge',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='jobrun',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='optionposition',
            options={'ordering': ('underlying', 'expiry', 'strike')},
        ),
        migrations.AlterModelOptions(
            name='orderrecord',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='portfoliosnapshot',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('symbol',)},
        ),
        migrations.AddField(
            model_name='decision',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user.userprofile'),
        ),
        migrations.AddField(
            model_name='hedge',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user.userprofile'),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user.userprofile'),
        ),
        migrations.AddField(
            model_name='optionposition',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user.userprofile'),
        ),
        migrations.AddField(
            model_name='orderrecord',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user.userprofile'),
        ),
        migrations.AddField(
            model_name='portfoliosnapshot',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user.userprofile'),
        ),
        migrations.AddField(
            model_name='position',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='optionposition',
            name='occ_symbol',
            field=models.CharField(help_text='OCC option symbol, e.g. AAPL250321C00150000', max_length=64),
        ),
        migrations.AlterField(
            model_name='position',
            name='symbol',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='optionposition',
            unique_together={('owner', 'occ_symbol')},
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('owner', 'symbol')},
        ),
    ]
