# Generated by Django 6.1 on 2026-09-13 10:56

import agent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_embeddedriskcontext_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='action',
            field=models.CharField(choices=[('hold', 'Hold'), ('hedge', 'Hedge (protective put)'), ('buy_stock', 'Buy stock'), ('cash_secured_put', 'Cash-secured put'), ('covered_call', 'Covered call'), ('spread', 'Spread'), ('unwind', 'Unwind / reduce risk'), ('emergency', 'Emergency flat'), ('close_hedge', 'Close hedge')], default='hold', max_length=32),
        ),
        migrations.AlterField(
            model_name='embeddedriskcontext',
            name='embedding_vector',
            field=agent.models.VectorStoreField(dimensions=4096, help_text='pgvector embedding of ``raw_text_chunk`` (text -> vector).'),
        ),
        migrations.AlterField(
            model_name='orderrecord',
            name='strategy',
            field=models.CharField(choices=[('protective_put', 'Protective Put'), ('hedge', 'Hedge'), ('unwind', 'Unwind'), ('emergency_flat', 'Emergency flat'), ('manual', 'Manual'), ('cash_secured_put', 'Cash-Secured Put'), ('covered_call', 'Covered Call'), ('spread', 'Spread'), ('buy_stock', 'Buy Stock')], default='manual', max_length=32),
        ),
    ]
